import { Document, Page, View, Text, Image, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  coverTitle: { fontSize: 28, marginBottom: 8 },
  coverSubtitle: { fontSize: 12, color: "#666666", marginBottom: 4 },
  sectionTitle: { fontSize: 16, marginBottom: 12, marginTop: 8 },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  cardSmall: { width: 140, marginBottom: 10 },
  cardLarge: { width: 240, marginBottom: 14 },
  image: { width: "100%", height: 100, objectFit: "cover", borderRadius: 4 },
  imageLarge: { width: "100%", height: 170, objectFit: "cover", borderRadius: 4 },
  caption: { fontSize: 8, color: "#888888", marginTop: 3 },
  label: { fontSize: 9, marginTop: 3 },
  table: { marginTop: 8 },
  tableRow: { flexDirection: "row", borderBottom: "1pt solid #dddddd", paddingVertical: 4 },
  tableCellLabel: { width: "60%", textTransform: "capitalize" },
  tableCellValue: { width: "40%", textAlign: "right" },
});

export type PresentationData = {
  venueName: string;
  eventType: string | null;
  guestCount: number | null;
  renders: { blobUrl: string; area: string | null }[];
  referencesByArea: { area: string; images: { blobUrl: string; styleTags: string[] | null }[] }[];
  bom: { category: string; count: number }[];
};

export function PresentationDocument({ data }: { data: PresentationData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.coverTitle}>{data.venueName}</Text>
        {data.eventType && <Text style={styles.coverSubtitle}>{data.eventType}</Text>}
        {data.guestCount && <Text style={styles.coverSubtitle}>{data.guestCount} guests</Text>}
        <Text style={{ ...styles.coverSubtitle, marginTop: 20 }}>
          Design presentation — generated by VenueAI
        </Text>
      </Page>

      {data.renders.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Decorated Venue Renders</Text>
          <View style={styles.grid}>
            {data.renders.map((r, i) => (
              <View key={i} style={styles.cardLarge}>
                {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer's Image has no alt prop; this isn't HTML img */}
                <Image style={styles.imageLarge} src={r.blobUrl} />
                {r.area && <Text style={styles.caption}>{r.area}</Text>}
              </View>
            ))}
          </View>
        </Page>
      )}

      {data.referencesByArea.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Moodboard</Text>
          {data.referencesByArea.map((group) => (
            <View key={group.area} style={{ marginBottom: 16 }}>
              <Text style={{ ...styles.label, textTransform: "capitalize", marginBottom: 6 }}>
                {group.area}
              </Text>
              <View style={styles.grid}>
                {group.images.map((img, i) => (
                  <View key={i} style={styles.cardSmall}>
                    {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer's Image has no alt prop; this isn't HTML img */}
                    <Image style={styles.image} src={img.blobUrl} />
                    {img.styleTags && img.styleTags.length > 0 && (
                      <Text style={styles.caption}>{img.styleTags.join(", ")}</Text>
                    )}
                  </View>
                ))}
              </View>
            </View>
          ))}
        </Page>
      )}

      {data.bom.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.sectionTitle}>Bill of Materials</Text>
          <View style={styles.table}>
            {data.bom.map((item) => (
              <View key={item.category} style={styles.tableRow}>
                <Text style={styles.tableCellLabel}>{item.category}</Text>
                <Text style={styles.tableCellValue}>{item.count}</Text>
              </View>
            ))}
          </View>
        </Page>
      )}
    </Document>
  );
}
